<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sumedh" failures="1" tests="6" name="Default test" time="347.607" errors="0" timestamp="2025-08-27T19:41:33 IST">
  <testcase classname="com.orangehrm.tests.AddEmployeeTest" name="testNavigateToAddEmployee" time="33.35"/>
  <testcase classname="com.orangehrm.tests.AddEmployeeTest" name="testAddEmployeeWithMandatoryFields" time="51.701"/>
  <testcase classname="com.orangehrm.tests.AddEmployeeTest" name="testAddEmployeeWithAllDetails" time="52.328"/>
  <testcase classname="com.orangehrm.tests.AddEmployeeTest" name="testAddEmployeeWithLoginDetails" time="84.484">
    <failure type="java.lang.AssertionError" message="Employee with login details not created successfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Employee with login details not created successfully expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.orangehrm.tests.AddEmployeeTest.testAddEmployeeWithLoginDetails(AddEmployeeTest.java:259)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testAddEmployeeWithLoginDetails -->
  <testcase classname="com.orangehrm.tests.AddEmployeeTest" name="testAddEmployeeValidation" time="34.991"/>
  <testcase classname="com.orangehrm.tests.AddEmployeeTest" name="testCancelAddEmployee" time="35.875"/>
</testsuite> <!-- Default test -->
